apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian13-vm
  namespace: default
  labels:
    app: debian13-vm
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: debian13-vm-root
      spec:
        source:
          http:
            url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
        storage:
          resources:
            requests:
              storage: 3Gi    
    - metadata:
        name: debian13-vm-data
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 2Gi
          # storageClassName: <la-tua-storageclass>   # opzionale, altrimenti usa la default
  template:
    metadata:
      labels:
        kubevirt.io/domain: debian13-vm
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: virtio
            - name: datadisk
              serial: datadisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: rootdisk
          dataVolume:
            name: debian13-vm-root
        - name: datadisk
          dataVolume:
            name: debian13-vm-data
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: debian
              password: debian
              chpasswd:
                expire: false
              ssh_pwauth: true
              hostname: debian13-vm
              fs_setup:
                - device: /dev/disk/by-id/virtio-datadisk
                  filesystem: ext4
                  partition: none
                  label: data
              mounts:
                - [ /dev/disk/by-id/virtio-datadisk, /data, ext4, "defaults,nofail", "0", "2" ]